### PR TITLE
JsProxy: object is array-like if it has length and is iterable

### LINKED ISSUE #5990: File references are not subscriptable
## 🐛 Bug

If there is an `<input type="file">` on the page and a listener to reach that `event.target.files[0]` an error about the object not being subscribe-able, as opposite of being handled just like any other regular object, is rised.

### To Reproduce

```html
<input id="file" type="file">
```

```python
from js import document

def onchange(envet):
    file = event.target.files[0]

document.querySelector('#file').onchange = onchange
```

### Expected behavior

`File` is just an *object* in JS world, sure thing it has a special meaning, but there's nothing special to it from any other regular objects.

### Environment

- Pyodide Version: latest
- Browser version: any
- Any other relevant information:

### PR DESCRIPTION
**Pull request by hoodmane**
Resolves #5990.

- [x] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry
- [x] Add / update tests

### CODE REVIEW

**Comment by hoodmane** [comment]
@WebReflection how's this look to you now?

**Comment by WebReflection** [comment]
@hoodmane clean and correct 👍

File: src/core/jsproxy.c [hunk 1]
```diff
@@ -57,7 +57,7 @@
 #define IS_BUFFER          (1 << 8)
 #define IS_CALLABLE        (1 << 9)
 #define IS_ARRAY           (1 << 10)
-#define IS_NODE_LIST       (1 << 11)
+#define IS_ARRAY_LIKE      (1 << 11)
```
Comment (ryanking13) [inline src/core/jsproxy.c:60]: Maybe it would be nice to add a comment about what the ARRAY_LIKE is here as well.

```
 * array-like objects like HTMLCollection or
 * NodeList, controlled by IS_ARRAY_LIKE
```

**Review by ryanking13 — COMMENTED** [review]
Thanks! It looks like there is a build error?

File: src/core/jsproxy.c (hunk 1 above)
Comment (hoodmane) [reply src/core/jsproxy.c:60]: If we want to add comments here, I'd think we should do it for everything all at once?
