### PR TITLE
Fix package loading race condition

### LINKED ISSUE #270: async imports don't play nicely with non-async ones
A Mozillian found an aspect of async importing that appears to not work. The code block below demonstrates the issue - it appears that mixing imports that fetch resources (other stuff from the pyodide stack) don't play very nicely with imports that don't.

You can replace the `from js import document` line with some other expected-to-work import statement that uses python and you get the same error, so it appears that this issue is caused by the async stuff in some way.

```
%%py
import matplotlib.pyplot as plt
from js import document
```

### PR DESCRIPTION
**Pull request by mdboom**
There was a fairly hard-to-reproduce race condition in how packages are loaded.

After the full set of packages to load are resolved, each of them is "loaded" by adding `<script>` elements to the end of the document.  When these package `.js` files are run, the first thing they do is increment a global counter, and call the `monitorRunDependencies` callback.  When each is done, that counter is decremented, and the same `monitorRunDependencies` callback is called.  Our `monitorRunDependencies` callback assumes everything is done (and the Python is ready to call) when that counter reaches 0.  However, in rare cases, the first few packages load and finish before all of the packages have started running, i.e., the counter follows a pattern like "1 2 3 4 5 4 3 2 1 0 1 2 1 0".  There doesn't seem to be a good way to do this reliably given how emscripten's API around this works, so the solution, since we know exactly how many packages we expect to load, is to just wait for the callback to be called exactly `npackages * 2` times.

I'm hoping this will resolve some of the random failures we've seen in CI.

Thanks @acmiyaguchi for finding the bug and helping me find the solution.

Fixes #270.

### CODE REVIEW

File: src/pyodide.js [hunk 1]
```diff
@@ -148,8 +148,11 @@ var languagePluginLoader = new Promise((resolve, reject) => {
         messageCallback(`Loading ${packageList}`);
       }
 
+      var packageCounter = Object.keys(toLoad).length * 2;
+
       window.pyodide._module.monitorRunDependencies = (n) => {
```
Comment (darthtrevino) [inline src/pyodide.js]: you don't need the `n` argument anymore here

Comment (mdboom) [reply src/pyodide.js]: Good point!

**Comment by mdboom** [comment]
I don't think we need to update the other `monitorRunDependencies` -- that exists only to handle the loading of a single resource (the main pyodide data file), so checking for `n === 0` is good enough there.  The signatures don't have to match, and it's part of emscripten's API which we aren't changing anyway.  (Javascript lets you omit arguments you don't need, and if any are passed in they are silently ignored...)
